---
title: ""
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Network Enrichment Significance Testing in Brain-Phenotype Association Studies
<!-- to do: list co-authors -->

[*Link to preprint*](https://www.biorxiv.org/content/10.1101/2023.11.10.566593v1)

### Software

Code is available for implementing NEST in both R and python on [GitHub](https://github.com/smweinst/NEST).

Contributors:

- Bin Li, M.Eng, Computer Science PhD Candidate at Temple University

- [Sarah Weinstein, Ph.D.](https://smweinst.github.io), Assistant Professor of Biostatistics at Temple University

Feel free to reach out with any comments/questions!  

### [NEST in python](https://github.com/smweinst/NEST/tree/main/Python)
*Installation from command line:*
<!-- Bin to update as needed -->

Install requirement dependents,
```bash
pip3 install scipy sklearn pandas matplotlib nibabel nilearn hcp_utils
```
Then install the NEST via pip,

```{python, include = T, eval = F, python.reticulate = F}
pip install NEST
```

Congradulations! The NES has been successfully installed.

#### Tutorial in Python



##### Step 1: import the NEST package after the installation.
```{python, include = T, eval = F, python.reticulate = F}
from nest-sw import nest
```
##### Step 2: Preparing the data and define the following dictionary of arguments passed to the nest method. The args can be defined as
```{python, include = T, eval = F, python.reticulate = F}
args = {
    'X': data,  # Hypothetical predictor variables, e.g., the 2-D brain-scan imaging data shaped as (sample_size, feature_size) in a numpy array format.
    'y': phenotype, # Hypothetical response variable, e.g., phenotypic data for samples corresponding to images, shaped as (sample_size, 1).
    'Z': covariate,  # Optionally specifying covariates, set to NULL here if you want to explicitly state no covariates.
    'FL': False,  # Optional, set to True to use Freedman-Lane permutation.
    'getNull': True,  # Optional, defult is True to explicitly stating to get a null distribution.
    'n_perm': 5   # Optional, default is 999. Override to specify the number of permutations. 
}
```
##### Step 3: Loading the labels of networks corresponding to each location in X, shaped as a binary array (feature_size,) for a specific parcellation. e.g., the default network from [yeo et al](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation).

##### The label should be assigned like 'network_labels = load_label_data()' if you have a function called load_label_data() to read labels from files.

##### Step 4: Calling the NEST method and get a list of return values:
```{python, include = T, eval = F, python.reticulate = F}
output = nest(statFun='lm',args=args,net_maps=network_labels)

print('The p-value from tests of enrichment is', output[0])

# output[0]: p-value
# output[1]: observed enrichment score
# output[2]: enrichment score for null distribution
```

### [NEST in R](https://github.com/smweinst/NEST/tree/main/R)
*Installation in R:*  
```{r, include = T, eval = F}
if (!require(devtools)){
  install.packages("devtools")
}
devtools::install_github("smweinst/NEST")
library(NEST)
```

#### Tutorial in R
[in progress]